### ISSUE TITLE
Syllabus table

### ISSUE THREAD

**Issue by jgeller112** [osrrl/osrrl.github.io#1]
@jvcasillas 

I am trying to recreate your syllabus table but am having a bit of trouble. What files do I need to tweak? 

Thanks!

**Comment by jvcasillas** [comment]
`data > lessons.yml` controls the content of the syllabus table: https://github.com/osrrl/osrrl.github.io/blob/main/data/lessons.yml

and `layouts > shortcodes > syllabus.html` controls the structure of the syllabus:
https://github.com/osrrl/osrrl.github.io/blob/main/layouts/shortcodes/syllabus.html

If you need more info or have any questions just let me know 👍🏼
